Guy:
   Press: 110
   Deadlift: 200
   Bench: 155
   Squat: 165
Liat:
    Press: 100
    Deadlift: 225
    Bench: 135
    Squat: 165
Gigi:
    Press: 115
    Deadlift: 275
    Bench: 195
Saar:
    Press: 145
    Deadlift: 275
    Bench: 225
    Squat: 165
